#!/bin/bash

if [[ -z $(ps -aux | grep -v grep | grep -w play) ]]; then
    echo "Music Player is not running."
    exit 1
fi
echo $(ps -aux | grep -v grep | grep -w play | egrep -o '/home.*mp3' | cut -d '.' -f 1 | rev | cut -d '/' -f 1 | rev)
