#!/bin/bash

homebin="$HOME/bin"
if [ ! -d "$homebin" ]; then
    mkdir $homebin
fi
cp `ls | grep -v "INSTALL" | grep -v "README.md"` $HOME/bin
if [[ -z $(cat ~/.bashrc | grep "export PATH=\$HOME/bin:\$PATH") ]]; then
    echo "Adding \$HOME/bin to path ..."
    echo "export PATH=\$HOME/bin:\$PATH" >> ~/.bashrc
fi
