#!/bin/bash

# Check if there is any current play process running
if [[ -z $(ps -aux | grep -v grep | grep -w play) ]]; then
    echo "Music Player is not running."
    exit 1
fi

# Get the playlist directory name
playlist_dir=$(dirname $(ps -aux | grep -v grep | grep -w play | awk '{print $12;}' | cut -d '.' -f 1))

# Check to see if there is any unreadable characters
if [[ $(current) == *"?"* ]]; then

    bad_current=$(current)
    IFS='?'
    read -ra current_file <<< "$bad_current"
    
    # Create a list of recognizable characters
    recognized=()
    for i in "${current_file[@]}"; do
        if [[ -n $i ]]; then
           recognized+=("$i")
        fi
    done
   
    # grep all the recognizable characters, only one file should contains all of them
    grepresult=$(cat $playlist_dir'/playlist')
    for i in "${recognized[@]}"; do
        grepresult=$(echo $grepresult | grep $i )
    done
   
    # Find the full file name of the current song
    real_current_file=$(echo $grepresult | rev | cut -d '/' -f 1 | rev | cut -d "'" -f 1)

    # Gets the line number of this song, and adds to the playlist
    current_number=$(grep -n $real_current_file $playlist_dir'/playlist' | cut -d ':' -f 1 | head -1)

    # Gets the current song based on the line number, -n: quiet 
    command_to_add=$(sed -n $current_number'p' $playlist_dir'/playlist')

    # Stops the current songs
    current_PID=$(ps -aux | grep -v grep | grep -w play | awk '{print $2;}')
    kill -STOP $current_PID

    # Plays the current song
    eval "$command_to_add"

    # Resume the current song
    kill -CONT $(ps -aux | grep -v grep | grep -w play | awk '{print $2;}')

else

    # Similar idea to above
    current_number=$(grep -n $(current) $playlist_dir'/playlist' | cut -d ':' -f 1 | head -1)
    command_to_add=$(sed -n $current_number'p' $playlist_dir'/playlist')

    current_PID=$(ps -aux | grep -v grep | grep -w play | awk '{print $2;}')
    kill -STOP $current_PID
    eval "$command_to_add"
    kill -CONT $(ps -aux | grep -v grep | grep -w play | awk '{print $2;}')
fi
