#!/bin/bash

if [[ -z $(ps -aux | grep -v grep | grep -w play) ]]; then
    echo "Music Player is not running."
    exit 1
fi

playlist_dir=$(dirname $(ps -aux | grep -v grep | grep -w play | awk '{print $12;}' | cut -d '.' -f 1))
echo $playlist_dir
if [[ $(current) == *"?"* ]]; then
    bad_current=$(current)
    IFS='?'
    read -ra current_file <<< "$bad_current"
    count=0
    recognized=0
    for i in "${current_file[@]}"; do
        if [[ -n $i ]]; then
           recognized=$count
        fi
        ((count +=1))
    done
    char=${current_file[$recognized]}
    current_file=$(grep -n $char $playlist_dir'/playlist' | cut -d ':' -f 1)
    echo "current file"
    echo $current_file
    current_number=$(grep -n $char $playlist_dir'/playlist' | cut -d ':' -f 1 | head -1)
    echo "1 Current Number : "
    echo $current_number
    command_to_add=$(sed -n $current_number'p' $playlist_dir'/playlist')
    echo "1 Command to add : "
    echo $command_to_add
    #sed "$current_number a $command_to_add" $playlist_dir'/playlist'

    current_PID=$(ps -aux | grep -v grep | grep -w play | awk '{print $2;}')
    kill -STOP $current_PID
#nohup eval "$command_to_add" >/dev/null 2>&1 &
    eval "$command_to_add"
#while kill -0 $(ps -aux | grep -v grep | grep -w play | awk '{print $2;}') 2> /dev/null; do sleep 1; done;
    kill -CONT $(ps -aux | grep -v grep | grep play | awk '{print $2;}')

else
    current_number=$(grep -n $(current) $playlist_dir'/playlist' | cut -d ':' -f 1 | head -1)
    command_to_add=$(sed -n $current_number'p' $playlist_dir'/playlist')
    echo "2 Command to add : "
    echo $command_to_add
    #sed "$current_number a $command_to_add" $playlist_dir'/playlist'

    current_PID=$(ps -aux | grep -v grep | grep -w play | awk '{print $2;}')
    kill -STOP $current_PID
#nohup eval "$command_to_add" >/dev/null 2>&1 &
    eval "$command_to_add"
#while kill -0 $(ps -aux | grep -v grep | grep -w play | awk '{print $2;}') 2> /dev/null; do sleep 1; done;
    kill -CONT $(ps -aux | grep -v grep | grep play | awk '{print $2;}')
fi
