#!/bin/bash

if [[ -z $(ps -aux | grep -v grep | grep -w play) ]]; then
    echo "Music Player is not running."
    exit 1
fi

playlist_dir=$(dirname $(ps -aux | grep -v grep | grep -w play | awk '{print $12;}' | cut -d '.' -f 1))
echo $playlist_dir
if [[ $(current) == *"?"* ]]; then
    bad_current=$(current)
    current_file=${bad_current%"?"}
    echo $current_file
else
    current_number=$(grep -n $(current) $playlist_dir'/playlist' | cut -d ':' -f 1)
    echo $current_number
fi
